name: simple_mysql_orm
version: 3.0.4
description: A simple ORM wrapper for mysql with Transaction support.
repository: https://github.com/bsutton/simple_mysql_orm
environment: 
  sdk: '>=2.16.1 <3.0.0'
dependencies: 
  collection: ^1.15.0
  date_time: ^0.6.0
  dcli: ^1.17.3
  galileo_mysql: ^3.0.0
  intl: ^0.17.0
  logging: ^1.0.2
  meta: ^1.7.0
  money2: ^3.1.2
  recase: ^4.0.0
  scope: ^2.2.0
  settings_yaml: ^3.3.1
dev_dependencies: 
  lint_hard: ^1.0.0
  test: ^1.19.5
executables: 
  build_dao: 
