name: simple_mysql_orm
version: 2.0.1
description: A simple ORM wrapper for mysql with Transaction support.
repository: https://github.com/bsutton/simple_mysql_orm
environment: 
  sdk: '>=2.16.0-80.1.beta <3.0.0'
dependencies: 
  date_time: ^0.5.0
  dcli: ^1.16.0
  dcli_core: ^0.0.5
  galileo_mysql: ^3.0.0
  intl: ^0.17.0
  logging: ^1.0.2
  meta: ^1.7.0
  money2: ^3.1.2
  scope: ^2.2.0
  settings_yaml: ^3.3.1
dev_dependencies: 
  lint_hard: ^1.0.0
  test: ^1.19.5
dependency_overrides: 
  scope: 
    path: ../scope
